name: Deploy Module
on:
  pull_request:
    types: [closed]
    branches-ignore:
      - main
  push:
    branches:
      - "**releases**"
      - "!develop"
      - "!main"

jobs:
  get-data:
    runs-on: ubuntu-latest
    steps:
      - name: Show Tag
        run: |
          echo "Tag ------> ${{ steps.determine_tag.outputs.tag }}"
          echo "Base Ref ------> ${{ github.base_ref }}"
          echo "Head Ref ------>  ${{ github.head_ref }}"
          echo "GitHub Ref ------> ${{ github.ref }}"
          echo "Event Name ------> ${{ github.event_name }}"

  # deploy main module
  validate-event-push:
      if: ${{ github.event_name == 'push' }}
      runs-on: ubuntu-latest
      steps:
        - name: Determine Tag
          id: determine_tag
          run: echo "::set-output name=tag::$(echo "${{ github.ref }}" | tr "[:upper:]" "[:lower:]" | grep -o "releases")"
        - name: Show Tag
          run: echo "${{ steps.determine_tag.outputs.tag }}"
      outputs:
        tag: ${{ steps.determine_tag.outputs.tag }}

  set-tag-event-push:
    needs: validate-event-push
    if: ${{ needs.validate-event-push.outputs.tag == 'releases' }} && ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine Tag
        id: determine_tag
        run: echo "::set-output name=tag::admin-panel-fe-$(echo "${{ github.ref }}" | tr "[:upper:]" "[:lower:]" | cut -d "/" -f 3 | cut -d "-" -f 1,2)"
      - name: Show Tag
        run: echo "${{ steps.determine_tag.outputs.tag }}"
    outputs:
      tag: ${{ steps.determine_tag.outputs.tag }}      

  # deploy secondary module
  validate-event-pull-request:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine Tag
        id: determine_tag
        run: echo "::set-output name=tag::$(echo "${{ github.base_ref }}" | tr "[:upper:]" "[:lower:]" | grep -o "releases")"
      - name: Show Tag
        run: echo "${{ steps.determine_tag.outputs.tag }}"
    outputs:
      tag: ${{ steps.determine_tag.outputs.tag }}

  set-tag-pull-request:
    needs: validate-event-pull-request
    if: ${{ needs.validate-event-pull-request.outputs.tag == 'releases' }} && ${{ github.event_name == 'pull_request' }} && ${{ github.base_ref == 'develop' }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine Tag
        id: determine_tag
        run: echo "::set-output name=tag::admin-panel-fe-$(echo "${{ github.head_ref }}" | tr "[:upper:]" "[:lower:]" | cut -d "/" -f 3 | cut -d "-" -f 1,2)"
      - name: Show Tag
        run: echo "${{ steps.determine_tag.outputs.tag }}"
    outputs:
      tag: ${{ steps.determine_tag.outputs.tag }}

  # init deploy main module

  deploy-module:
    needs: set-tag-event-push
    if: ${{ needs.set-tag-event-push.tag != '' }} && ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Show Tag
        run: echo "Tag ------> ${{ needs.set-tag-event-push.outputs.tag }}"

  # init deploy secondary module
  delete-module:
    needs: set-tag-pull-request
    if: ${{ needs.set-tag-pull-request.tag != '' }} && ${{ github.event_name == 'pull_request' }} && ${{ github.base_ref == 'develop' }}
    runs-on: ubuntu-latest
    steps:
      - name: Show Tag
        run: echo "Tag ------> ${{ needs.set-tag-pull-request.outputs.tag }}"
