name: Deploy Module
on:
  pull_request:
    types: [closed]
    branches-ignore:
      - main
  push:
    branches:
      - "**releases**"
      - "!develop"
      - "!main"

jobs:
  preview-github-data:
    runs-on: ubuntu-latest
    steps:
      - name: Show Tag Preview GitHub Data
        run: |
          echo "Tag ------> ${{ steps.determine_tag.outputs.tag }}"
          echo "Base Ref ------> ${{ github.base_ref }}"
          echo "Head Ref ------>  ${{ github.head_ref }}"
          echo "GitHub Ref ------> ${{ github.ref }}"
          echo "Event Name ------> ${{ github.event_name }}"

  # deploy main module
  validate-event-push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Determine Tag
        id: determine_tag
        run: echo "::set-output name=tag::$(echo "${{ github.ref }}" | tr "[:upper:]" "[:lower:]" | grep -o "releases")"
      - name: Show Tag
        run: echo "${{ steps.determine_tag.outputs.tag }}"
    outputs:
      tag: ${{ steps.determine_tag.outputs.tag }}

  set-tag-event-push:
    runs-on: ubuntu-latest
    needs: validate-event-push
    if: ${{ needs.validate-event-push.outputs.tag == 'releases' }}
    steps:
      - name: Determine Tag
        id: determine_tag
        run: echo "::set-output name=tag::admin-panel-fe-$(echo "${{ github.ref }}" | tr "[:upper:]" "[:lower:]" | cut -d "/" -f 3 | cut -d "-" -f 1,2)"
      - name: Show Tag
        run: echo "${{ steps.determine_tag.outputs.tag }}"
    outputs:
      tag: ${{ steps.determine_tag.outputs.tag }}

  build-docker-image:
    runs-on: ubuntu-latest
    needs: set-tag-event-push
    if: ${{ needs.set-tag-event-push.outputs.tag == 'tbr' }}
    steps:
      - name: Determine Tag
        id: determine_tag
        run: echo "::set-output name=tag::admin-panel-fe-$(echo "${{ github.ref }}" | tr "[:upper:]" "[:lower:]" | cut -d "/" -f 3 | cut -d "-" -f 1,2)"
      - name: Show Tag
        run: echo "${{ steps.determine_tag.outputs.tag }}"
    outputs:
      tag: ${{ steps.determine_tag.outputs.tag }}

  validate-event-pull-request:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Determine Tag
        id: determine_tag
        run: echo "::set-output name=tag::$(echo "${{ github.base_ref }}" | tr "[:upper:]" "[:lower:]" | grep -o "releases")"
      - name: Show Tag
        run: echo "${{ steps.determine_tag.outputs.tag }}"
    outputs:
      tag: ${{ steps.determine_tag.outputs.tag }}

  set-tag-pull-request:
    runs-on: ubuntu-latest
    needs: validate-event-pull-request
    if: ${{ needs.validate-event-pull-request.outputs.tag == 'releases' }}
    steps:
      - name: Determine Tag
        id: determine_tag
        run: echo "::set-output name=tag::admin-panel-fe-$(echo "${{ github.head_ref }}" | tr "[:upper:]" "[:lower:]" | cut -d "/" -f 3 | cut -d "-" -f 1,2)"
      - name: Show Tag
        run: echo "${{ steps.determine_tag.outputs.tag }}"
    outputs:
      tag: ${{ steps.determine_tag.outputs.tag }}

  init-deploy-module:
    runs-on: ubuntu-latest
    needs: build-docker-image
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Show Tag Deploy Module
        run: echo "DEPLOY MODULE ${{ github.event_name }}"

  init-delete-module:
    runs-on: ubuntu-latest
    needs: set-tag-pull-request
    if: ${{ github.base_ref == 'develop' }}
    steps:
      - name: Show Tag Delete Module
        run: echo "DELETE MODULE ${{ github.base_ref }}"
