name: Deploy Modules
on:
  pull_request:
    types: [opened, synchronize, closed, reopened]
    branches-ignore:
      - master
  push:
    branches:
      - develop

jobs:
  validate-branch-name:
    runs-on: self-hosted
    steps:
      - name: Determine Tag
        id: determine_tag
        run: echo "::set-output name=tag::$(echo "${{ github.head_ref }}" | tr "[:upper:]" "[:lower:]" | grep -o "tbr")"
      - name: Show Tag
        run: echo "Tag is ${{ steps.determine_tag.outputs.tag }}"
    outputs:
      tag: ${{ steps.determine_tag.outputs.tag }}