name: Deploy Module
on:
  pull_request:
    types: [closed]
    branches-ignore:
      - main
  push:
    branches:
      - "**releases**"
      - "!develop"
      - "!main"

jobs:
  get-data:
    runs-on: ubuntu-latest
    steps:
      - name: Show Tag
        run: |
          echo "Tag ------> ${{ steps.determine_tag.outputs.tag }}"
          echo "Base Ref ------> ${{ github.base_ref }}"
          echo "Head Ref ------>  ${{ github.head_ref }}"
          echo "GitHub Ref ------> ${{ github.ref }}"
          echo "Event Name ------> ${{ github.event_name }}"

  # deploy main module
  validate-event-push:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine Tag
        id: determine_tag
        run: echo "::set-output name=tag::$(echo "${{ github.ref }}" | tr "[:upper:]" "[:lower:]" | grep -o "releases")"
      - name: Show Tag
        run: echo "${{ steps.determine_tag.outputs.tag }}"
    outputs:
      tag: ${{ steps.determine_tag.outputs.tag }}

  set-tag-event-push:
    needs: validate-event-push
    if: ${{ needs.validate-event-push.outputs.tag == 'releases' }} && ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine Tag
        id: determine_tag
        run: echo "::set-output name=tag::admin-panel-fe-$(echo "${{ github.ref }}" | tr "[:upper:]" "[:lower:]" | cut -d "/" -f 3 | cut -d "-" -f 1,2)"
      - name: Show Tag
        run: echo "${{ steps.determine_tag.outputs.tag }}"
    outputs:
      tag: ${{ steps.determine_tag.outputs.tag }}

  build-docker-image:
    needs: set-tag-event-push
    if: ${{ needs.set-tag-event-push.outputs.tag == 'tbr' }} && ${{ github.event_name == 'push' }}
    runs-on: self-hosted
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: asia-southeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Pre Build
        run: "docker system prune -af && docker system prune --volumes -af"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: asia-southeast1-docker.pkg.dev/scamo-group/toberich-stag/${{ needs.set-tag-event-push.outputs.tag }}:latest
    outputs:
      image: asia-southeast1-docker.pkg.dev/scamo-group/toberich-stag/${{ needs.set-tag-event-push.outputs.tag }}@${{ steps.docker_build.outputs.digest }}
      tag: ${{ needs.set-tag-event-push.outputs.tag }}

  validate-event-pull-request:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine Tag
        id: determine_tag
        run: echo "::set-output name=tag::$(echo "${{ github.base_ref }}" | tr "[:upper:]" "[:lower:]" | grep -o "releases")"
      - name: Show Tag
        run: echo "${{ steps.determine_tag.outputs.tag }}"
    outputs:
      tag: ${{ steps.determine_tag.outputs.tag }}

  set-tag-pull-request:
    needs: validate-event-pull-request
    if: ${{ needs.validate-event-pull-request.outputs.tag == 'releases' }} && ${{ github.event_name == 'pull_request' }} && ${{ github.base_ref == 'develop' }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine Tag
        id: determine_tag
        run: echo "::set-output name=tag::admin-panel-fe-$(echo "${{ github.head_ref }}" | tr "[:upper:]" "[:lower:]" | cut -d "/" -f 3 | cut -d "-" -f 1,2)"
      - name: Show Tag
        run: echo "${{ steps.determine_tag.outputs.tag }}"
    outputs:
      tag: ${{ steps.determine_tag.outputs.tag }}

  init-deploy-module:
    needs: build-docker-image
    if: ${{ github.event_name == 'push' }} && ${{ github.base_ref != 'develop' }} && ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
    - name: Show Tag
      run: echo "DEPLOY MODULE"

  init-delete-module:
    needs: set-tag-pull-request
    if: ${{ github.base_ref == 'develop' }} && ${{ github.event_name == 'pull_request' }} && ${{ github.event_name != 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Show Tag
        run: echo "DELETE MODULE"